#:schema https://www.schemastore.org/treefmt.json
# SPDX-FileCopyrightText: 2024 Tomodachi94
#
# SPDX-License-Identifier: MIT

# One CLI to format the code tree - https://github.com/numtide/treefmt

[formatter.ruff]
command = "ruff"
options = ["format"]
includes = ["*.py"]

[formatter.nixpkgs-fmt]
command = "nixpkgs-fmt"
includes = ["*.nix"]

[formatter.taplo]
command = "taplo"
options = ["fmt"]
includes = ["*.toml"]

[formatter.yamlfmt]
command = "yamlfmt"
includes = ["*.yaml", "*.yml"]
